name: Send a Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Hi, this is a test!"
          twitter-app-key: ${{ secrets.TWITTER_APP_CONSUMER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_CONSUMER_API_SECRET_KEY }}
          twitter-access-token: ${{ secrets.TWITTER_APP_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ TWITTER_APP_ACCESS_TOKEN_SECRET }}
