name: publish-to-twitter
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: devigned/go-twitter-action@v1
        with:
          message: "Hey folks we just release a new version of ACME widgets!"
          apiKey: ${{ secrets.API_KEY }}
          apiKeySecret: ${{ secrets.API_KEY_SECRET }}
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          accessTokenSecret: ${{ secrets.ACCESS_TOKEN_SECRET }}
