# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Write to CSV file
  # You may pin to the exact commit or the version.
  # uses: gr2m/write-csv-file-action@f8dc162c9df0ed4d82a734e02efec73f6d252293
        uses: gr2m/write-csv-file-action@v1.0.0
        with:
    # Relative path to .csv file (example: data/stats.csv)
          path: data/stats.csv
    # Comma separated list of column titles. Inputs with the same names must be set
          columns: a,b,c
